<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>vro.action.log</string>
        <key>name</key>
        <string>Log file</string>
        <key>patterns</key>
        <array>

            <!-- Quoted strings with " -->
            <dict>
                <key>match</key>
                <string>"(.*?)"</string>
                <key>name</key>
                <string>string.quoted vrdev.log.string</string>
            </dict>

            <!-- Quoted strings with ' -->
            <dict>
                <key>match</key>
                <string>'(.*?)'</string>
                <key>name</key>
                <string>string.quoted vrdev.log.string</string>
            </dict>

            <!-- GUID -->
            <dict>
                <key>match</key>
                <string>\b(?i:([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}))\b</string>
                <key>name</key>
                <string>support.class vrdev.log.guid</string>
            </dict>

            <!-- Exception type names -->
            <dict>
                <key>match</key>
                <string>\b([a-zA-Z.]*(Exception|Error))\b</string>

                <key>name</key>
                <string>string.regexp vrdev.log.exception</string>
            </dict>

            <!-- Colorize rows of exception call stacks -->
            <dict>
                <key>begin</key>
                <string>^[\t ]*at</string>

                <key>end</key>
                <string>$</string>

                <key>name</key>
                <string>string.key, emphasis vrdev.log.callStack</string>
            </dict>

            <!-- ISO dates ("2016-08-23") -->
            <dict>
                <key>match</key>
                <string>\b\d{4}-\d{2}-\d{2}(T|\b)</string>

                <key>name</key>
                <string>constant.numeric vrdev.log.date</string>
            </dict>

            <!-- Culture specific dates ("23/08/2016", "23.08.2016") -->
            <dict>
                <key>match</key>
                <string>\b\d{2}[^\w\s]\d{2}[^\w\s]\d{4}\b</string>

                <key>name</key>
                <string>constant.numeric vrdev.log.date</string>
            </dict>

            <!-- Clock times with optional timezone ("09:13:16", "09:13:16.323", "09:13:16+01:00") -->
            <dict>
                <key>match</key>
                <string>\d{1,2}:\d{2}(:\d{2}([.,]\d{1,})?)?(Z| ?[+-]\d{1,2}:\d{2})?\b</string>

                <key>name</key>
                <string>constant.numeric vrdev.log.date</string>
            </dict>

            <!-- Numeric (decimal) -->
            <dict>
                <key>match</key>
                <string>\b\d+\.?\d*?\b</string>
                <key>name</key>
                <string>constant.numeric vrdev.log.numeric</string>
            </dict>

            <!-- Numeric (hex) -->
            <dict>
                <key>match</key>
                <string>\b(?i:(0?x)?[0-9a-f][0-9a-f]+)\b</string>
                <key>name</key>
                <string>constant.numeric vrdev.log.numeric</string>
            </dict>

            <!-- Namespace -->
            <dict>
                <key>match</key>
                <string>\b(?i:(([a-z]|[0-9]|[_|-])*(\.([a-z]|[0-9]|[_|-])*)+))\b</string>
                <key>name</key>
                <string>support.type vrdev.log.namespace</string>
            </dict>

            <dict>
                <key>match</key>
                <string>\b(?i:(error|failure|fail|fatal))(\:|\b)</string>
                <key>name</key>
                <string>storage.type vrdev.log.error</string>
            </dict>

            <dict>
                <key>match</key>
                <string>\b(?i:(info|information|true|false|log))(\:|\b)</string>
                <key>name</key>
                <string>markup.inserted vrdev.log.info</string>
            </dict>

            <dict>
                <key>match</key>
                <string>\b(?i:(warning|warn|test|null|undefined|NaN))(\:|\b)</string>
                <key>name</key>
                <string>markup.deleted vrdev.log.warning</string>
            </dict>

            <dict>
                <key>match</key>
                <string>\b(?i:(debug|fine|finest))(\:|\b)</string>
                <key>name</key>
                <string>comment.line vrdev.log.debug</string>
            </dict>

            <!-- Generic URI/URL -->
            <dict>
                <key>match</key>
                <string>\b(?i:([a-z]|[0-9])+\:((\/\/)|((\/\/)?(\S)))+)</string>
                <key>name</key>
                <string>storage vrdev.log.url</string>
            </dict>

            <dict>
                <key>begin</key>
                <string>^#</string>
                <key>end</key>
                <string>$\n?</string>
                <key>name</key>
                <string>comment.line vrdev.log.comment</string>
            </dict>
        </array>
        <key>uuid</key>
        <string>ea07944a-a028-4bf3-9d39-cd79e6fefd14</string>
    </dict>
</plist>
